### ISSUE TITLE
[App] Add responsiveness Home page tablet

### ISSUE THREAD

**Issue by ConstancePetillot** [bpaquier/sansa-project-hetic#131]
## Contexte
Tablette

## Description

Afin que notre app borne soit visible sur toutes les tablettes (peut importe leur taille), nous devons rendre nos pages plus responsive. 

- **Pour cela, il faut rajouter du scroll sur la home page pour que tous les élements soient visible.**

Sur une plus petite tablette que du 20'', les textes se chevauchent rendant la lecture impossible.

![image.png](https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/2d205fe3-8b4e-4626-a205-66879736bdfc)

- [x]  Ajouter les clefs de trad sur la page

- [x]  Enlever les border au onPress

- [x] Changer le bloc "Sport" pour un bloc "Hebergement"

![image](https://user-images.githubusercontent.com/56641493/178231256-af2694b0-ee72-4d34-aa62-04b09190e724.png)

**Comment by Klochette** [comment]
Le bloc sport a été changé dans la branche de @njsen
