### ISSUE TITLE
[Back Office] Reduce Footer size

### ISSUE THREAD

**Issue by ConstancePetillot** [bpaquier/sansa-project-hetic#137]
## Contexte
Desktop

## Description
Le footer était trop grand sur la maquette, nous l'avons donc réduit. 
Il faut faire les modifs sur le site :

Actuellement : 
![image.png](https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/74321d05-1aab-4730-90e8-e80478689148)

Maquette : 
![image.png](https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/50a806ef-8c6d-463e-baec-d5d9e254560f)

Prendre comme point de repère le point jaune :
![image.png](https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/d8d9c4b6-7e31-4558-91a0-5ef3f9c17563)

**Comment by intisar91** [comment]
- [x] Footer Desktop réduit 

![image](https://user-images.githubusercontent.com/69139728/178120667-3af8134a-1985-4d2e-a14b-e9a1321fec1e.png)

Idem pour le mobile

<img width="410" alt="image" src="https://user-images.githubusercontent.com/69139728/178120758-135f9afd-7a46-4d04-96d0-74632ef39584.png">

**Comment by intisar91** [comment]
PR Open: https://github.com/hugoborini/Sansa_api/pull/34

**Comment by ConstancePetillot** [comment]
Hello @intisar91,

C'est tout bon pour la taille du footer et la position de l'image.

Est-ce que tu peux juste changer ton breakpoint du mobile vers le desktop à 600px pour être sûre que rien ne casse ? 
Merci !

![image](https://user-images.githubusercontent.com/56641493/178148833-3a082dd7-8985-4940-878f-5b567c05b3df.png)

**Comment by intisar91** [comment]
@ConstancePetillot je viens de le changer à 600px :)
