### ISSUE TITLE
[Back Office] Fix Nav bar

### ISSUE THREAD

**Issue by ConstancePetillot** [bpaquier/sansa-project-hetic#147]
## Contexte
Mobile et Desktop

### Général :

- [x] Il y a un scroll horizontal en mobile et sur desktop: à supprimer.

- [ ] Mettre le header en sticky pour qu'il reste toujours en haut de la page.

### Sur mobile :

- [x] La page qui s'ouvre du menu doit faire 100% de la height 

<img src="https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/d11c7a36-572b-4d18-9643-27c61dd38c8d"  width="300"/>

- [x] L'animation sur le burger menu et la croix est bizarre. Faire juste un changement entre burger et croix sans 14 rotations

### Sur Desktop : 

- [x] Le hover sur les bouton "inscription" et "connexion" ne marche plus.

- [x] Le bouton "connexion" est collé au bord de l'écran à droite.

**Le site :**
![image.png](https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/107f407d-e45b-4dbe-af44-2137447b7e73)

**La maquette :**
![image.png](https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/802603f3-929f-45c8-beb1-7f76546bd20f)

**Comment by intisar91** [comment]
PR open :  https://github.com/hugoborini/Sansa_api/pull/35
