### ISSUE TITLE
Add Checkbox components

### ISSUE THREAD

**Issue by ConstancePetillot** [bpaquier/sansa-project-hetic#26]
## Contexte
Toute l'app

## Description
Ajouter les composants de checkbox à l'UI kit

Bien respecter les états et le nommage

<img width="446" alt="image" src="https://user-images.githubusercontent.com/47388675/171881397-b73f59f0-2282-403b-8935-8c0d07f84935.png">

**Comment by bpaquier** [comment]
@Klochette j'ai intégré la checkbox dans le form du register, j'ai juste adapté le changement d'état pour qu'il remonte dans le submit du form, et j'ai réduit la taille du texte pour etre iso maquette   :) 

@ConstancePetillot ok pour moi. Sauf pour les liens inlines, on en a parlé avec Aurore et toi vite fait, galere pour nous pour l'instant de faire des liens inlines avec un style particulier. ici peut on les supprimer? surtout qu'on a pas de page avec les conditions générales et la politique de confidentialité.
