### ISSUE TITLE
[Back Office] Creating homepage Navbar 

### ISSUE THREAD

**Issue by NawelBrrch** [bpaquier/sansa-project-hetic#64]
## Contexte
Desktop / Création de la navbar du back office 

## Description
La nav bar du back office comprends : 

- [ ] logo Sansa cliquable qui ramène vers la homepage. 

- [ ] Un lien "nos valeurs" 

- [ ] Un lien "notre solution"

- [ ] Un CTA inscription

- [ ] Un CTA connexion

<img width="600" alt="image" src="https://user-images.githubusercontent.com/56641493/174990997-4c2fcd10-21b1-44a8-9c53-83a9ab93f659.png">

La maquette du BO est en 1440px mais doit malgré tout être responsive sur les ecrans 13" ou sur les écrans plus grands.

## Maquette

Figma > ✅ Ready to Dev ✅ > Back Office

**Comment by ConstancePetillot** [comment]
https://github.com/hugoborini/Sansa_api/pull/5

**Comment by ConstancePetillot** [comment]
Review https://github.com/hugoborini/Sansa_api/pull/5
