### ISSUE TITLE
[Back Office] Creating homepage Footer

### ISSUE THREAD

**Issue by ConstancePetillot** [bpaquier/sansa-project-hetic#69]
## Contexte
Desktop
## Description

Développer le composant du footer de la homepage du site Vitrine.
Il n'y a pour l'instant aucun lien sur les élements du Footer. Certains seront rajoutés éventuellement.

Ne pas oublier le disclaimer tout en bas à droite.

![image.png](https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/47889b4a-600e-42a8-ac27-d4d80b397ce2)

## 🖼 Maquette

Figma > ✅ Ready to dev ✅ > Back Office

**Comment by ConstancePetillot** [comment]
@intisar91 Est-ce que tu peux mettre le lien de ta PR s'il te plait ?

**Comment by intisar91** [comment]
@ConstancePetillot yes ^^
PR: https://github.com/hugoborini/Sansa_api/pull/8
