### ISSUE TITLE
[App] Which translation library ?

### ISSUE THREAD

**Issue by ConstancePetillot** [bpaquier/sansa-project-hetic#73]
## Contexte
App

## Description

Le MVP de notre app comporte la possibilité à un utilisateur de selectionné une langue parmis 5 langues :

- Français

- Anglais

- Arabe

- Espagnol

- Ukrainien

 Il faut donc faire un benchmark des différentes library et autres solutions possible qui permettrait la traduction facile de notre app.

Les différentes solutions peuvent être présentées sur un doc qui permettra à l'équipe de faire un choix final.

**Comment by Klochette** [comment]
https://github.com/s0ftik3/reverso-api

**Comment by Klochette** [comment]
https://github.com/vitalets/google-translate-api
