### ISSUE TITLE
[Back Office] Footer homepage Mobile

### ISSUE THREAD

**Issue by ConstancePetillot** [bpaquier/sansa-project-hetic#88]
## Contexte
Mobile

## Description

Développer le composant du footer de la homepage du site Vitrine.
Il n'y a pour l'instant aucun lien sur les élements du Footer. Certains seront rajoutés éventuellement.

Ne pas oublier le disclaimer tout en bas à droite.

<img width="300" alt="image" src="https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/752195b0-56be-4652-8a64-08d539659c40">

## 🖼 Maquette

Figma > ✅ Ready to dev ✅ > Site vitrine

**Comment by intisar91** [comment]
PR: https://github.com/hugoborini/Sansa_api/pull/8
