### ISSUE TITLE
[Back Office] Header homepage mobile

### ISSUE THREAD

**Issue by ConstancePetillot** [bpaquier/sansa-project-hetic#89]
## Contexte
Mobile

## Description

Développer le header du site vitrine sur mobile

**Header** 

<img width="400" alt="image" src="https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/318305ff-2e2e-4c21-b7d0-3710bfe8399d">

**Menu burger ouvert**

<img width="300" alt="image" src="https://images.zenhubusercontent.com/5fca7441f5c7da266a5e5fe4/79c58b4f-3823-452f-833e-f23cb7849a57">

## À Noter

- Au click sur le logo du header, la page remonte sur le hero header.

## Maquettes 🖼

Figma -> ✅ Ready to dev ✅ -> Site vitrine

**Comment by intisar91** [comment]
PR link https://github.com/hugoborini/Sansa_api/pull/31
